name: "Push Docker Image to Dev ECR"
on:
  workflow_dispatch:
  push:
    branches:
      - rp-OPS-147-automate-build
jobs:
  build_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::381491835868:role/GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build Docker image
        run: |
          docker build -t flink-k8s-operator .

      - name: Tag Docker image
        run: |
          docker tag flink-k8s-operator:latest 381491835868.dkr.ecr.us-east-1.amazonaws.com/flink-k8s-operator:latest

      - name: Push Docker image to ECR
        run: |
          docker push 381491835868.dkr.ecr.us-east-1.amazonaws.com/flink-k8s-operator:latest
