name: "Push Docker Image to ECR"
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'release-*'
jobs:
  build_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure dev AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::381491835868:role/GithubActionsRole
          aws-region: us-east-1

      - name: Login to Amazon dev ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Configure prod AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::992382778380:role/GithubActionsRole
          aws-region: us-east-1

      - name: Login to Amazon prod ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Publish Docker image to prod ECR
        run: |
          TAG="1.9.0-${GITHUB_SHA::7}"
          docker buildx build \
            --tag 381491835868.dkr.ecr.us-east-1.amazonaws.com/flink-k8s-operator:$TAG \
            --tag 992382778380.dkr.ecr.us-east-1.amazonaws.com/flink-k8s-operator:$TAG \
            --platform=linux/amd64,linux/arm64 --push --file Dockerfile .
