name: "Push Docker Image to ECR"
on:
  workflow_dispatch:
    inputs:
      aws_account:
        description: AWS Account ID
        required: true
        default: '381491835868'
        type: choice
        options:
          - '381491835868' # dev
          - '430118825661' # staging
          - '992382778380' # prod
  push:
    branches:
      - main
      - 'release-*'
jobs:
  build_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    env:
      AWS_ACCOUNT_ID: ${{ github.event.inputs.aws_account || '381491835868' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: release-1.9

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Publish Docker image to ECR (${{ env.AWS_ACCOUNT_ID }})
        run: |
          TAG="1.9.0-${GITHUB_SHA::7}"
          docker buildx build \
            --tag ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/flink-k8s-operator:$TAG \
            --platform=linux/amd64,linux/arm64 --push --file Dockerfile .
